version: 1.0.{build}
image: Visual Studio 2015

environment:
    python2_version: 2.7.15
    python3_version: 3.6.6
    tcl32_version: 8.6.6.8607
    tcl32_revision: 403667
    tcl64_version: 8.6.7.0
    tcl64_revision: 404764
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          arch: 32
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          arch: 64
install:
    - dir c:\Python27
    - ps: appveyor\variables.ps1
    - ps: appveyor\install.ps1
    - npm install win-sqlcipher
    - npm install
    - npm rebuild zeromq --runtime=electron --target=1.8.4
    - pip install -r requirements.txt

build_script:
    - npm install

test_script:
    - python appveyor\test.py --msvc %msvc%
    - python appveyor\check.py --python2-version %python2_version% --python3-version %python3_version% --tcl-version %tcl_version%

deploy_script:
    - dir c:\

