version: 1.0.{build}
image: Visual Studio 2015

environment:
    python2_version: 2.7.15
    python3_version: 3.6.6
    tcl32_version: 8.5.18.0
    tcl32_revision: 403667
    tcl64_version: 8.5.18.0
    tcl64_revision: 404764
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          arch: 32
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          arch: 64
install:
    - dir C:\
    - ps: appveyor\variables.ps1
    - ps: appveyor\install.ps1
    - git clone https://github.com/journeyapps/node-sqlcipher.git
    - tar -xvzf node-sqlcipher/deps/sqlcipher-amalgamation-3020001.tar.gz
    - dir sqlcipher-amalgamation-3020001
    - npm install --save "@journeyapps/sqlcipher"
    - dir sqlite3.h /s
    - pip install --verbose pysqlcipher3
#    - npm rebuild zeromq --runtime=electron --target=1.8.4
#    - pip install -r requirements.txt

build_script:
    - npm install

test_script:
    - python appveyor\test.py --msvc %msvc%
    - python appveyor\check.py --python3-version %python3_version% --tcl-version %tcl_version%

deploy_script:
    - dir c:\

